server:
  port: 0
  
spring:
  application:
    name: user
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    
logging:
  level:
    org:
      hibernate:
        sql: debug

